package model;

public enum PacketType {
    SIGN_UP_REQ,
    SIGN_IP_RES,
    LOG_IN_REQ,
    LOG_IN_RES,
    CHANGE_SETTING_REQ,
    CHANGE_SETTING_RES,
    DELETE_USER_REQ,
    DELETE_USER_RES,
    LOG_OUT_REQ,
    LOG_OUT_RES,
    SETTING_INFO_REQ,
    SETTING_INFO_RES,
    BYE
}